export const  REQUEST_GET_DATA_START ="REQUEST_GET_DATA_START"
export const  REQUEST_GET_DATA_COMPLETED = 'REQUEST_GET_DATA_COMPLETED'
export const  REQUEST_GET_DATA_ERROR = 'REQUEST_GET_DATA_ERROR'

export const  CHANGE_ADDRESS_LOCAL = 'CHANGE_ADDRESS_LOCAL'

export const  SEARCH_LOCAL_START = 'SEARCH_LOCAL_START'
export const  SEARCH_LOCAL_COMPLETED = 'SEARCH_LOCAL_COMPLETED'
export const  SEARCH_LOCAL_ERROR = 'SEARCH_LOCAL_ERROR'